from fastmcp import FastMCP
import fatools
import json

mcp = FastMCP("famcp")

#-----------------------Shared Funtions Begin----------------------------------- 

#load server configuration from local JSON file named serverconf.json.
with open("serverconf.json", "r") as sconf:
  server_conf:dict = json.load(sconf)

server_ip:str = server_conf["server_ip"]
server_port:int = server_conf["server_port"]

#load array info which saved in a local JSON file named fainfo.json.
with open("fainfo.json","r") as fainfo:
  array_info : dict = json.load(fainfo)

#check if array infor is predefined in config file(fainfo.json).
def Get_Array_Info(array_name:str) -> dict:
  current_array:dict = {
    "array_name":"",
    "api_token":""
  }
  
  for i in array_info["array_info"]:
    if i["array_name"] == array_name:
      current_array["array_name"] = i["array_name"]
      current_array["api_token"] = i["api_token"]
  
  return current_array

#-----------------------Shared Functions End----------------------------------- 

# tool for listing all volumes' information
@mcp.tool()
def Get_Volumes(array_name:str) -> json:
  """
    List all existing volumes and related information on a given Everpure FlashArray.

    Args:
      array_name: The IP address or FQDN of the management port of the specific Everpure FlashArray. REQUIRED.    
    
    Returns:
      A JSON object with list of volumes and parameters of each volume. Here are the structure and explaination of each parameter:
      {
        'id': The hash ID of the volume generated by FlashArray. Value type is 'str'.
        'name': The name of the volume. Value type is 'str'. There will be a '::' in the string if the volume is in a pod. Before '::' is pod name. After '::' is the volume name itself. 
        'connection_count': The number of connections between the volume and host(s). Value type is 'int'. 
        'created': The creation time of the volume. The value type is 'int'. Original in Linux EPOC time format. Need to be always converted to 'HH:MM:SS MM-DD-YYYY' format.
        'destroyed': 'Fales' if the volume is not destroyed. 'True' if the volume is destroyed but still in recycle bin and has not been eradicated yet. 
        'host_encryption_key_status': Reflecting whether the host encryption is enabled. 'none' for not enabled.
        'priority_adjustment': Read cache settings. Just ignore it. 
        {
          'priority_adjustment_operator': Just ignore it.
          'priority_adjustment_value': Just ignore it.
        }
        'provisioned': The provsioned volume size of the volume. The value type is 'int'. Originally count in byte, always covert it to GiB/MiB(if less than 1 GiB). 
        'qos': Quality of Service settings.
        {
          'bandwidth_limit': The bandwidth limit of the volume. The value type is 'int'. Original in byte, always convert to GiB or MiB(if less than 1 GiB).
          'iops_limit': Then IOPS limit of the volume. The value type is 'int'.
        }
        'serial': The serial number of the volume.
        'space': The space related information of the volume.
        {
          'data_reduction': The Data Reduction Rate of then volume. Value type is 'float'. Always round to 2 dencimal places for easy reading.
          'snapshots': The number of volume only snapshots. Protection group snapshots not included. The value type is 'int'.
          'thin_provisioning': Just ignore it.
          'total_physical': Just ignore it.
          'total_provisioned': Just ignore it.
          'total_reduction': Just ignore it.
          'total_used': Just ignore it.
          'unique': Just ignore it.
          'used_provisioned': Just ignore it.
          'virtual': The used space of the volume. The value type is 'int'. Original in byte, always convert to GiB/MiB(if less than 1 GiB).
        }
        'context': Just ignore it.
        {
          'id': Just ignore it.
          'name': Just ignore it.
        }
        'pod': The pod information if the volume is in a pod.
        {
          'id': The hash ID of the pod generated by FlashArray. The value type is 'str'.
          'name': The pod name which the volume belongs to.
        }
        'priority': Just ignore it.
        'promotion_status': Just ignore it.
        'protocol_endpoint': Just ignore it.
        'requested_promotion_state': Just ignore it.
        'source': To be updated. Just ignore it by now.
        'subtype': Just ignore it.
        'volume_group': The volume group information of the volume.
        {
          'id': The hash ID of the volume group generated by FlashArray.
          'name': The name of the volume group which the volume is belongs to.
        }
      }
  """
  current_array = Get_Array_Info(array_name)
  
  if current_array["array_name"] == "":
    return "ERROR: Array not found in config file. Please add it first!"

  current_client = fatools.Create_FA_Client(current_array)
  results:json = json.dumps(fatools.Get_Volumes(current_client), indent=4)
  
  return results


#tool for creating a volume
@mcp.tool()
def Create_One_Volume(array_name:str, volume_name:str, volume_size:int) -> str:
  """
    Create a storage volume on a specific Everpure FlashArray.

    Args:
      array_name: The IP address or FQDN of the management port of the specific Everpure FlashArray. REQUIRED.
      volume_name: The name of the volume. REQUIRED.
      volume_size: The size of the volume. The unit is GB. REQUIRED.

    Returns:
      Results of the job. 
  """
  current_array = Get_Array_Info(array_name)
  
  if current_array["array_name"] == "":
    return "ERROR: Array not found in config file. Please add it first!"

  current_client = fatools.Create_FA_Client(current_array)
  results = fatools.Create_One_Volume(current_client,volume_name, volume_size)
  
  return results

# tools for creating a host
@mcp.tool()
def Create_One_Host(array_name:str, host_name:str, protocol_type:str, endpoint_ids:list[str], personality:str = "") -> str:
  """
    Create a host on a given Everpure FlashArray

    Args:
      array_name: The IP address or FQDN of the management port of the specific Everpure FlashArray. REQUIRED.
      host_name: The name of the host to be created on the array. REQUIRED.
      protocol_type: The protocol to be used to connect host and the array. Should be one of fc/iscsi/nvme. REQUIRED.
      endpoint_ids: The protocol related IDs. WWN for fc, IQN for iscsi, NQN for nvme. REQUIRED.
      personality: Determines how the system tunes the array to ensure that it works optimally with the host. Set personality to the name of the host operating system or virtual memory system. Valid values are aix, esxi, hitachi-vsp, hpux, oracle-vm-server, solaris, vms, nutanix-mgmt and nutanix-cluster. If your system is not listed as one of the valid host personalities, do not set the option. By default, the personality is not set.

    Returns:
      Results of the job.
  """

  # Check if the given array name is in the configuration file
  current_array = Get_Array_Info(array_name)
  if current_array["array_name"] == "":
    return "ERROR: Array not found in config file. Please add it first!"

  current_client = fatools.Create_FA_Client(current_array)
  results: str = fatools.Create_One_Host(current_client,host_name,protocol_type,endpoint_ids,personality)
  
  return results

# tool for creating a host group
@mcp.tool()
def Create_Host_Group(array_name:str, host_group_name:str) -> str:
  """
    Create a host group on a given Everpure FlashArray

    Args:
      array_name: The IP address or FQDN of the management port of the specific Everpure FlashArray. REQUIRED.
      host_group_name: The name of the host group to be created on the array. REQUIRED.

    Returns:
      Results of the job.
  """

  # Check if the given array name is in the configuration file
  current_array = Get_Array_Info(array_name)
  if current_array["array_name"] == "":
    return "ERROR: Array not found in config file. Please add it first!"

  current_client = fatools.Create_FA_Client(current_array)
  results:str = fatools.Create_Host_Group(current_client,host_group_name)
  
  return results

# tool for adding hosts into a given host group
@mcp.tool()
def Add_Host_To_Host_Group(array_name:str, host_name:str, host_group_name:str) -> str:
  """
    Add a host into a given host group on an Everpure FlashArray

    args:
      array_name: The IP address or FQDN of the management port of the specific Everpure FlashArray. REQUIRED.
      host_name: The name of a host which will be added into a given host group. REQUIRED.
      host_group_name: The name of the host group the host to be added to. REQUIRED.

    Returns:
      Results of the job.
  """
  # Check if the given array name is in the configuration file
  current_array = Get_Array_Info(array_name)
  if current_array["array_name"] == "":
    return "ERROR: Array not found in config file. Please add it first!"

  current_client = fatools.Create_FA_Client(current_array)
  results:str = fatools.Add_Host_To_Host_Group(current_client, host_name, host_group_name)

  return results


# tool for connecting a volume to a host
@mcp.tool()
def Connect_Volume_To_Host(array_name:str,host_name:str, volume_name:str) -> str:
  """
    Connect a pre-created volume to a pre-created host on a specific Everpure FlashArray.

    Args:
      array_name: The IP address or FQDN of the management port of the specific Everpure FlashArray. REQUIRED.
      host_name: The name of the host which was defined on the given Everpure FlashArray and will connect to the given volume. REQUIRED.
      volume_name: The name of the volume which was created before and will be connected to the given host or host group. REQUIRED.

    Returns:
      Results of the job.
  """
  # Check if the given array name is in the configuration file
  current_array = Get_Array_Info(array_name)
  if current_array["array_name"] == "":
    return "ERROR: Array not found in config file. Please add it first!"

  current_client = fatools.Create_FA_Client(current_array)
  results: str = fatools.Connect_Volume_To_Host(current_client,host_name,volume_name)

  return results

# tool for creating a snapshot from a volume
@mcp.tool()
def Create_Volume_Snapshot(array_name:str, volume_name:str="", snapshot_name:str="") -> str:
  """
    Create a snapshot from a given volume on given Everpure FlashArray.

    Args:
      array name: The IP address or FQDN of the management port of the specific Everpure FlashArray.
      volume name: The name of the volume which snapshot will be created from.
      snapshot name: The name of the snapshot.

    Returns:
      The results of the job.
  """
  current_array = Get_Array_Info(array_name)
  if current_array["array_name"] == "":
    return "ERROR: Array not found in config file. Please add it first!"

  current_client = fatools.Create_FA_Client(current_array)
  results: str = fatools.Create_Volume_Snapshot(current_client,volume_name,snapshot_name)

  return results

if __name__ == "__main__":
  mcp.run(transport="streamable-http", host=server_ip, port=server_port)
